"use client";
import {useEffect,useRef,useState} from 'react';
import {schedules,transportForSlot,isSlotEnabled,setSlotChoice,spotDetails,nearest,mapSearch} from './trip-options';
import {rates} from './hotel-rates';
import {destinations,sources,checkItems,type Photo,type Hotel} from './travel-data';
const iso=(n:number)=>`2026-10-${String(n).padStart(2,'0')}`;
const date=(n:number)=>`10月${n}日`;
const weekdays=['日','一','二','三','四','五','六'];
function Link({href,children}:{href:string;children:React.ReactNode}){return <a href={href} target="_blank" rel="noopener noreferrer">{children} ↗</a>}
export default function Home(){
 const [start,setStart]=useState(2),[selected,setSelected]=useState('taining');
 const [gallery,setGallery]=useState<{photos:Photo[];index:number}|null>(null);
 const [checked,setChecked]=useState<number[]>([]);const dialog=useRef<HTMLDialogElement>(null),touch=useRef(0);
 const [slots,setSlots]=useState<Record<string,boolean>>({});
 useEffect(()=>{try{setSlots(JSON.parse(localStorage.getItem('holiday-slots-v2')||'{}'))}catch{}},[]);
 function toggleSlot(i:number,j:number,value:boolean){setSlots(prev=>{const next=setSlotChoice(d.id,start,i,j,value,prev);try{localStorage.setItem('holiday-slots-v2',JSON.stringify(next))}catch{}return next})}
 const d=destinations.find(x=>x.id===selected)!;
 useEffect(()=>{try{setChecked(JSON.parse(localStorage.getItem('travel-2026-checklist')||'[]'))}catch{}},[]);
 useEffect(()=>{if(gallery){dialog.current?.showModal();document.body.style.overflow='hidden'}else{dialog.current?.close();document.body.style.overflow=''}return()=>{document.body.style.overflow=''}},[!!gallery]);
 const move=(n:number)=>setGallery(g=>g?{...g,index:(g.index+n+g.photos.length)%g.photos.length}:g);
 function Photos({photos}:{photos:Photo[]}){return <div className="photos">{photos.map((p,i)=><figure key={p.file}><button className="photo" onClick={()=>setGallery({photos,index:i})} aria-label={`放大：${p.caption}`}><img src={p.file} alt={p.caption} loading="lazy"/><span>⤢ {photos.length>1?`${i+1} / ${photos.length}`:'查看实景'}</span></button><figcaption>{p.caption} <Link href={p.source}>图片来源</Link></figcaption></figure>)}</div>}
 function HotelCard({h}:{h:Hotel}){const current=rates[h.id]?.[start];return <article className="hotel"><Photos photos={h.photos}/><div className="hotel-body"><span className="eyebrow">{h.priority}</span><h3>{h.name}</h3><p className="muted">{h.area} · 计划住{h.nights}晚</p><div className={current?.state==='quoted'?'quote-badge':'pending'}>{current?.state==='quoted'?(h.nights===1?'已查到单晚报价 · 当前低于¥1200':'已查到大床均价 · 逐晚明细仍待确认'):current?.state==='unavailable'?'该日期目前不可预订':'待核价候选 · 不保证符合预算'}</div><p><b>大床筛选：</b>{current?.room||h.room}</p><p><b>推荐理由：</b>{h.plus}</p><p><b>需要取舍：</b>{h.minus}</p><p><b>最近行程景点：</b>{nearest[h.id]?.place} · {nearest[h.id]?.distance}</p><p><b>其他接驳：</b>{h.distance}</p><div className="map-links"><Link href={mapSearch(h.name)}>酒店位置搜索</Link><Link href={mapSearch(nearest[h.id]?.place||h.name)}>最近景点地图</Link></div><p><b>早餐与接驳：</b>{h.breakfast}</p><div className="rate-dates">{[2,3].map(n=>{const r=rates[h.id]?.[n];return <div key={n} className={start===n?'active':''}><strong>{date(n+h.offset)}入住 → {date(n+h.offset+h.nights)}退房</strong><span>1间大床 · 2位成人 · {h.nights}晚</span>{r?.state==='quoted'?<><div className="rate-price">¥{r.price}<em> / {h.nights===1?'1晚':'晚 · 连住均价'}</em></div><span>{r.room}</span><span>早餐：{r.breakfast}</span><span>取消：{r.cancel}</span>{r.nightly&&<span className="nightly">逐晚：{r.nightly}</span>}</>:<b className="unverified">{r?.state==='unavailable'?'目前不可预订':'报价 / 大床库存待核实'}</b>}<p>{r?.note}</p><Link href={'https://hotels.ctrip.com/hotels/detail/?hotelId='+h.id+'&checkin='+iso(n+h.offset)+'&checkout='+iso(n+h.offset+h.nights)}>携程复核该日期</Link></div>})}</div>{current?.state==='unavailable'&&<p className="pending">飞猪已核查（2026-08-31）：10月2日—5日、10月3日—6日，1间、2成人，详情页均显示“此酒店暂时没有可售房型”。未取得大床报价、含早套餐与取消条件；不代表已经售罄，原因仍需酒店确认。<Link href={'https://hotel.fliggy.com/hotel_detail2.htm?shid=57295333&city=350400&checkIn='+iso(start)+'&checkOut='+iso(start+3)+'&roomNum=1&aNum_1=2&cNum_1=0'}>飞猪复核当前日期</Link> 酒店页面所列电话：0598-7786666。</p>}<small>核查于2026-08-30登录后的可见房型列表，可能含会员优惠，未提交订单或锁价。进入携程请再次确认日期、大床、2人和含税总价。每家展示2张客房内景与2张外观。标“房型未核实”的内景不代表报价大床房；只有明确注明“对应报价房型”的照片可据此对照。</small></div></article>}
 return <><header className="top"><a href="#" className="brand"><span className="brand-icon">山</span>山海之间<span className="brand-sub">TRAVEL NOTES / 2026</span></a><a href="#compare">三地对比</a><a href="#hotels">住宿候选</a><button className="print" onClick={()=>window.print()}>打印当前方案 ↗</button></header>
 <main><section className="hero"><img src="images/qiandao.jpg" alt="千岛湖群岛航拍，来源浙江在线"/><div className="hero-shade"/><div className="hero-content"><p className="eyebrow">A SLOW HOLIDAY · OCTOBER 2026</p><h1>2026国庆<br/>山海慢旅行</h1><p>从福州出发，四天三晚。<br/>看风景、逛古城，按半天自由选择。</p><a className="hero-cta" href="#compare">找到适合你的四天 <span>↓</span></a></div><span className="hero-caption">千岛湖实景 · 浙江在线 / 航拍视角</span><div className="hero-index">03<span>个目的地<br/>一份慢旅行指南</span></div></section>
 <section className="trip-bar wrap"><div><span className="eyebrow">YOUR HOLIDAY</span><h2>先选日期，再看去哪里。</h2><p>福州鼓楼区往返 · 2位成人 · 1间大床 · 每晚预算≤¥1200</p></div><div className="dates" aria-label="出行日期">{[2,3].map(n=><button key={n} aria-pressed={start===n} className={start===n?'active':''} onClick={()=>setStart(n)}><strong>10.{String(n).padStart(2,'0')} — 10.{String(n+3).padStart(2,'0')}</strong><span>{n===2?'周五出发 · 周一返程':'周六出发 · 周二返程'}</span></button>)}</div></section>
 <div className="wrap"><details className="date-explain"><summary>两组日期有什么不同？<span>没有依据认为哪组一定更便宜或人更少 ＋</span></summary><div className="two-col"><p><b>10月2日—5日：</b>住宿为2、3、4日三晚，返程后还留6、7日缓冲；适合想在家再歇两天的人。去程预计9月18日起售，返程9月21日起售。</p><p><b>10月3日—6日：</b>住宿为3、4、5日三晚，返程后留7日缓冲；适合出发前多一天准备。去程预计9月19日起售，返程9月22日起售。</p></div><p>两组同处国庆假期、重叠3日和4日两晚。目前查到蓝湾同一景观大床含双早均价为863元与769元，假日雅致大床不含早为1096元与994元，华大轻享大床含双早两组均为862元。这只是这些房型的当次报价，不能推断整体更便宜或人更少。以上起售日按12306现行15天预售期推算，具体起售时刻按车站查询。</p><Link href={sources.holiday}>2026年假期安排</Link> · <Link href={sources.rail}>12306预售期说明</Link></details></div>
 <section className="wrap section" id="compare"><div className="section-title"><div><span className="eyebrow">01 / CHOOSE YOUR ESCAPE</span><h2>三种风景，三种过法。</h2></div><p>按休闲程度与转场成本比较，<br/>不做没有依据的“人少保证”。</p></div><div className="destination-grid">{destinations.map((x,i)=><button className={`destination-card ${selected===x.id?'selected':''}`} key={x.id} onClick={()=>{setSelected(x.id);document.getElementById('guide')?.scrollIntoView({behavior:'smooth'})}} aria-label={`查看${x.name}完整方案`}><div className="destination-image"><img src={x.cover.file} alt={x.cover.caption}/><span>0{i+1} / {x.theme}</span></div><div className="destination-copy"><span className="eyebrow">{x.en}</span><h3>{x.name}<span>↗</span></h3><b>{x.rank}</b><p>{x.mode}<br/>{x.intensity}<br/>{x.stay}</p><div className="card-foot">两人规划预算 ¥{x.total}<small>估算，非已核价套餐</small></div></div></button>)}</div><div className="recommend"><b>我的建议</b><p>喜欢山水、愿意开车：优先泰宁；想以酒店休息为核心且不想长途驾驶：千岛湖；更爱海与闽南美食、能接受较长返程：漳州＋东山。若只选最省驾驶精力，选千岛湖铁路方案。</p></div></section>
 <section id="guide" className="guide"><nav className="guide-nav"><div className="wrap nav-inner"><div className="dest-tabs" aria-label="目的地">{destinations.map(x=><button key={x.id} aria-pressed={selected===x.id} onClick={()=>setSelected(x.id)} className={selected===x.id?'active':''}>{x.name}</button>)}</div><div className="anchor-links"><a href="#itinerary">逐日行程</a><a href="#transport">交通</a><a href="#hotels">酒店</a><a href="#budget">预算</a></div><span className="nav-date">10.{start} — 10.{start+3}</span></div></nav>
 <div className="wrap"><section className="destination-intro section"><span className="eyebrow">{d.en} / {date(start)}—{date(start+3)}</span><h2>{d.headline}</h2><p className="lead">{d.intro}</p><div className="two-col reasons"><div><h3>值得选它的理由</h3>{d.good.map(t=><p key={t}><span className="reason-mark">＋</span>{t}</p>)}</div><div><h3>先接受这些取舍</h3>{d.bad.map(t=><p key={t}><span className="reason-mark">−</span>{t}</p>)}</div></div></section>
 <section id="itinerary" className="section"><div className="section-title"><div><span className="eyebrow">02 / FOUR SLOW DAYS</span><h2>按半天，选择你的行程。</h2></div><p>以下是计划窗口，不是已预约班次。<br/>下方直接列出所住酒店的接驳时间。</p></div><div className="slot-help"><p>勾选显示具体游玩安排；取消后才显示“休息或自行安排”。默认每套方案除去程、返程外，最多2个半天不勾选；默认关闭的时段也备有活动，勾上即可查看。去程、返程及跨城转场固定保留；短休穿插在活动时段内，不算整半天休息。同一区域的景点连续游玩，就近午餐与茶歇，尽量不绕回酒店；酒店接驳按候选酒店分别列出。</p><p>千岛湖、大金湖为跨半天的固定游船产品：上午开始、下午继续，两个时段联动勾选。上午/下午分别列出小景点，实际停靠顺序与时间以船方为准；不能单独取消半程。夜间返程不计饭后活动。默认首三晚安排2晚饭后活动；晚间不计入半天休息额度。选择仅保存在当前浏览器，两组日期分别记忆；已手动调整过可点“恢复当前推荐”。</p><button onClick={()=>{const next={...slots};Object.keys(next).filter(k=>k.startsWith(d.id+'-'+start+'-')).forEach(k=>delete next[k]);setSlots(next);try{localStorage.setItem('holiday-slots-v2',JSON.stringify(next))}catch{}}}>恢复当前推荐</button></div><div className="days">{schedules[d.id].map((periods,i)=><article className="day" key={d.id+i}><aside><span className="day-number">0{i+1}</span><b>{date(start+i)} · 周{weekdays[new Date(2026,9,start+i).getDay()]}</b><span className="stay">☾ {d.days[i].stay}</span></aside><div className="day-content">{periods.map((period,j)=>{const key=d.id+'-'+start+'-'+i+'-'+j;const enabled=isSlotEnabled(d.id,start,i,j,slots);return <section className={enabled?'period':'period rest'} key={key}><label className="period-toggle"><input type="checkbox" checked={!!enabled} disabled={period.locked} onChange={e=>toggleSlot(i,j,e.target.checked)}/><b>{period.label}</b><span>{period.locked?'必要交通 · 固定保留':enabled?(period.group?'完整游船 · 上下午联动':'推荐安排'):'休息或自行安排'}</span></label>{enabled?<div><p className="transfer"><b>本时段交通 · 规划估算</b><br/>{transportForSlot(d.id,start,i,j,slots)}</p>{d.trains.length>0&&period.locked&&<p className="muted">铁路信息沿用2026-08-30核查的近期参考时刻，国庆尚未开售；出发前以12306为准。<a href="#transport">查看车次来源与开售提醒 →</a></p>} {period.stops.length?period.stops.map((stop,k)=><div className="stop" key={k}><time>{stop.time}</time><div><h4>{stop.title}</h4><p>{stop.detail}</p>{stop.travel&&<p className="transfer"><b>↳ 交通</b> {stop.travel}</p>}</div></div>):null}{period.sight!==undefined&&<a className="spot-link" href={'#sight-'+d.id+'-'+period.sight}>查看{d.sights[period.sight].name}介绍与图片 →</a>}</div>:<p className="rest-copy">休息或自行安排 · 用餐按需；已预约的船班、入住退房及跨时段交通仍需遵守。</p>}</section>})}</div></article>)}</div></section>
 <section className="section" id="sights"><div className="section-title"><div><span className="eyebrow">03 / THE PLACES</span><h2>风景值得看，体力也要算。</h2></div><p>点击实景图片放大；多图可横滑。<br/>资料照片不代表届时天气与人流。</p></div><div className="sights-grid">{d.sights.map(s=><article className="sight" id={'sight-'+d.id+'-'+d.sights.indexOf(s)} key={s.name}><Photos photos={s.photos}/><div className="sight-body"><span className="eyebrow">{s.tag}</span><h3>{s.name}</h3><p>{s.reason}</p><details className="spot-detail" open><summary>建议看什么、怎么玩</summary>{spotDetails[s.name]?.map(t=><p key={t}>{t}</p>)}</details><p><b>体力与风险：</b>{s.caution}</p><p className="muted"><b>费用参考：</b>{s.cost}</p><p className="muted"><b>时间安排：</b>{s.hours}</p><div className="map-links"><Link href={s.source}>景点资料 / 出发前复核</Link><Link href={mapSearch(s.name)}>景点位置搜索</Link></div></div></article>)}</div><div className="weather"><span>☂</span><div><h3>雨天、停航、排队过长时</h3><p>{d.rain}</p><p>排队预计超过60分钟时，优先取消可选项目；先确认退改规则，改为附近用餐、室内休息。雷雨时不以另一个户外水景作为替代。</p></div></div><details className="alternatives"><summary>想换一种玩法？看替换路线和不推荐项目 ＋</summary>{d.alternatives.map(t=><p key={t}>{t}</p>)}{d.id==='zhangzhou'&&<Link href={sources.tulou}>南靖土楼官方资料</Link>}</details></section>
 <section className="section" id="transport"><div className="section-title"><div><span className="eyebrow">04 / GETTING THERE</span><h2>把路上的时间，也安排好。</h2></div><span className="status">规划估算 · 非实时路况</span></div><h3>{d.transport.title}</h3><div className="table-scroll"><table><thead><tr>{['路段','出发 / 方式','里程与时间','费用 / 缓冲依据'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{d.transport.rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div><p>{d.transport.note}</p><p className="muted">估算依据：公开城市间道路里程作尺度，按酒店位置追加接驳；车程并非导航实时结果。出租/包车为人工预算预留，未经司机报价；自驾按燃油车约0.6—0.8元/公里加停车与道路费用预留，新能源按实际补能调整。出发前一天用高德/百度地图核对实际酒店入口和路况。</p><p className="map-note">高德起终点路线待核验：当前地点查询要求登录，尚未取得可靠坐标。本页保留的链接暂为位置搜索，不是已完成的驾车导航。交通时间为规划估算，不是实时地图计算结果。</p><div className="source-links"><Link href={sources.road}>城市间道路资料</Link><Link href={sources.road2}>福州—漳州里程参考</Link><Link href={sources.road3}>东山—福州里程参考</Link><Link href="https://www.amap.com/">高德地图复核</Link></div>
 {d.trains.length>0&&<div className="rail"><h3>铁路：可查到的近期参考车次</h3><div className="pending"><b>国庆尚未开售，没有查询到国庆余票。</b>下列时刻于2026-08-30查阅公开页面；仅作为行程参考，最终以12306目标日期实际开行与时刻为准。</div><div className="table-scroll"><table><thead><tr>{['用途','车次','出发站 / 时间','到达站 / 时间','历时','说明'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{d.trains.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div><div className="release"><strong>当前日期方案：去程9月{start===2?'18':'19'}日 / 返程9月{start===2?'21':'22'}日预计开售</strong><p>15天预售期含乘车当天。起售钟点因车站不同，打开12306“起售时间”查询；不要到午夜才开始盲等。</p><Link href="https://www.12306.cn/">12306官方查询及购票</Link></div><div className="source-links">{d.trainSources.map(s=><Link key={s.url} href={s.url}>{s.label}</Link>)}</div></div>}</section>
 <section className="section" id="hotels"><div className="section-title"><div><span className="eyebrow">05 / STAY A LITTLE LONGER</span><h2>住得舒服，比多跑一站重要。</h2></div><p>1间大床 · 2位成人<br/>每晚硬上限 ¥1200</p></div><div className="hotel-disclaimer"><h3>已登录携程核查：报价、房型和退改条件分别列出。</h3><p>已按两组行程对应的实际入住日期查询1间、2成人，并核对可见大床房、早餐和取消条件。页面标“均”的价格是连住平均每晚价；除明确列出逐晚明细的房型外，仍不能确认每晚都≤1200元。房量及会员价格随时变化，以最后结算页面为准。</p><p>若湖景/海景大床超预算，先去掉景观升级、再比较位置备选；仍无合适房源时更换目的地或日期，不擅自加预算。东山品质优先与近南门湾的位置通常需要取舍。</p></div><div className="hotels-grid">{d.hotels.map(h=><HotelCard key={h.id} h={h}/>)}</div></section>
 <section id="budget" className="section budget"><div><span className="eyebrow">06 / TRAVEL BUDGET</span><h2>两个人，心里有个数。</h2><p>四天三晚，不含购物。以主推交通方式计算。<br/>价格均为预算分配，不是平台已报价总额。</p><div className="total">¥{d.total}<span>两人合计 / 估算</span></div><small>住宿硬上限3晚共¥3600，但未列明的逐晚房价仍待确认。若早餐另购、增加包车或景区产品升级，请重新核算。</small></div><div className="budget-rows">{d.budget.map(r=><div key={r[0]}><b>{r[0]}</b><strong>¥{r[1]}</strong><p>{r[2]}</p></div>)}</div></section></div></section>
 <section className="wrap section" id="checklist"><div className="section-title"><div><span className="eyebrow">BEFORE YOU GO</span><h2>出发前，确认这八件事。</h2></div><p>勾选只保存在当前浏览器。<br/>不会自动预订，也不会发送任何个人信息。</p></div><div className="checklist">{checkItems.map((c,i)=><label key={c}><input type="checkbox" checked={checked.includes(i)} onChange={()=>{const v=checked.includes(i)?checked.filter(x=>x!==i):[...checked,i];setChecked(v);try{localStorage.setItem('travel-2026-checklist',JSON.stringify(v))}catch{}}}/><span>{c}</span></label>)}</div><details className="method"><summary>资料来源、核查范围与图片说明 ＋</summary><p><b>报价核查：2026年8月30日；景点与图片补充：2026年8月31日。</b>已核实指公开页面中可读到的信息，不等于已向运营方确认国庆安排。景点开放、船班、门票及道路管制仍应在出发前复核；未来天气不能由资料图推断。</p><p><b>参考信息：</b>近期铁路时刻、景点公开介绍、酒店位置与设施。<b>规划估算：</b>车程、费用、步行距离、排队缓冲和两人总预算。<b>未核实：</b>国庆火车余票、未展示的酒店库存/逐晚明细、待核价酒店的早餐和取消政策，以及国庆船班。已读到的酒店报价与退改条件标在各卡片，均不代表锁价。</p><p>新增景点细项参考淳安融媒体中心的岛屿介绍（仅引用景观信息，不沿用历史票价与航班）、九龙潭官网及福建省政府文旅资料。<Link href="https://www.qdhnews.com.cn/content/content_8988103.html">千岛湖岛屿介绍</Link> · <Link href="https://zfgb.fujian.gov.cn/7450">泰宁景观资料</Link></p><p>图片来自各卡片所标注的媒体、官方网页或携程酒店/景点页，仅展示对应实景。航拍、历史照片与晴天照片均非当日效果承诺；酒店照片不代表所订楼栋和客房。图片版权归原作者/权利人所有，无AI实景替代图。</p><div className="source-links"><Link href={sources.tainingOfficial}>福建省政府·泰宁文旅资料</Link><Link href={sources.dongshan}>福建省政府·东山文旅资料</Link><Link href={sources.qdh}>浙江在线·千岛湖</Link><Link href={sources.holiday}>国庆假期安排</Link></div></details></section>
 </main><footer><div className="wrap"><div className="brand">山海之间<span className="brand-sub">2026 · 国庆行程规划</span></div><p>风景不用赶，假期慢慢过。</p><small>福州鼓楼区出发 · 更新于2026.08.31 · 独立旅行规划，非旅行社套餐</small></div></footer>
 <dialog ref={dialog} className="lightbox" onCancel={()=>setGallery(null)} onClick={e=>{if(e.target===e.currentTarget)setGallery(null)}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();setGallery(null)}if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1)}}><button className="close" onClick={()=>setGallery(null)} aria-label="关闭图片">×</button>{gallery&&<div className="lightbox-inner" onTouchStart={e=>touch.current=e.touches[0].clientX} onTouchEnd={e=>{const diff=e.changedTouches[0].clientX-touch.current;if(Math.abs(diff)>45)move(diff<0?1:-1)}}><img src={gallery.photos[gallery.index].file} alt={gallery.photos[gallery.index].caption}/><div className="lightbox-controls"><button onClick={()=>move(-1)} aria-label="上一张" disabled={gallery.photos.length<2}>←</button><span aria-live="polite">{gallery.index+1} / {gallery.photos.length}</span><button onClick={()=>move(1)} aria-label="下一张" disabled={gallery.photos.length<2}>→</button></div><p>{gallery.photos[gallery.index].caption}</p><Link href={gallery.photos[gallery.index].source}>原始图片来源</Link><small>可用左右方向键或手机滑动切换；Esc关闭</small></div>}</dialog></>;
}
